FROM bitnami/kafka:latest

# Optional: Set environment variables directly here (better handled in docker-compose though)
ENV KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 \
    ALLOW_PLAINTEXT_LISTENER=yes
